name: Build / deploy staging.training.plone.org

on:
  push:
    branches:
      - "nuclia"
    workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging.training.plone.org
      url: https://staging.training.plone.org
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q -r requirements.txt -c constraints.txt
          pip freeze

      - name: Prepare deploy
        run: make deploy

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY_TRAINING}}
        with:
          flags: "-avzr --delete"
          options: ""
          ssh_options: "-p ${{vars.DEPLOY_PORT_TRAINING}}"
          src: "_build/html/"
          dest: "${{vars.DEPLOY_USER_TRAINING}}@${{vars.DEPLOY_SERVER_TRAINING}}:${{vars.DEPLOY_PATH_TRAINING}}"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
