name: Build and deploy training documentation to 2022.training.plone.org

on:
  push:
    branches:
      - "2022"

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: 2022
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q -r requirements.txt -c constraints.txt

      - name: Prepare deploy
        run: make deploy

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY_TRAINING}}
        with:
          flags: "-avzr --delete"
          options: ""
          ssh_options: "-p ${{secrets.DEPLOY_PORT}}"
          src: "_build/html/"
          dest: "${{secrets.DEPLOY_USER_TRAINING}}@${{secrets.DEPLOY_SERVER_TRAINING}}:${{secrets.DEPLOY_PATH_TRAINING}}"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
